#!/bin/bash

myHour=$(date +'%H')
myMin=$(date +'%M')

brightnessctl -d nv_backlight set 100%
echo "no" > /usr/local/bin/myScripts/makeComputerUnusable/shouldComputerBecomeUnusableToday.txt
echo "yes" > /usr/local/bin/myScripts/screenshotScripts/shouldPromptsAppear.txt
echo "Turned on computer at: $myHour:$myMin" > /usr/local/bin/myScripts/screenshotScripts/partialPromptContent.txt
echo "00" > /usr/local/bin/myScripts/smartBulbScripts/dimmingTime.txt

chmod a+rw /usr/local/bin/myScripts/makeComputerUnusable/shouldComputerBecomeUnusableToday.txt
chmod a+rw /usr/local/bin/myScripts/screenshotScripts/shouldPromptsAppear.txt
chmod a+rw /usr/local/bin/myScripts/screenshotScripts/partialPromptContent.txt
chmod a+rw /usr/local/bin/myScripts/smartBulbScripts/dimmingTime.txt

#/usr/local/sbin/uploadToNotion/uploadDayToNotion
